### ISSUE TITLE
[US] Books: migrate users

### ISSUE THREAD

**Issue by ludmilamarian** [CERNDocumentServer/cds-migrator-kit#14]

**Comment by zzacharo** [comment]
After some investigation on how to migrate users there are some things to be addressed.

- [ ] Iterate through the list of users and clean up users that don't have valid accounts at Cern (in case we want to remove some trash data).
  - [ ] In case we do that we should update the loans of these users with a custom id (e.g -1) in order to keep the loans for statistics purposes but having a way to identify these cases.
- [ ] We need to keep the postbox information of the logged in user. There are possibly 2 solutions on that. Either we extend the Cern Oauth response to give back the postbox from `/Me` endpoint and then change https://github.com/inveniosoftware/invenio-oauthclient/blob/master/invenio_oauthclient/contrib/cern.py#L196 to integrate these information inside linked accounts or as also suggested by Anne in the library to have at least a link to the phonebook which is feasible as we keep the ccid and we can compose the link.
