### ISSUE TITLE
[US] Books: migrate access rights 

### ISSUE THREAD

**Issue by ludmilamarian** [CERNDocumentServer/cds-migrator-kit#3]
Migrate the access rights for books. In principle, all book records on CDS are public, but maybe there are some corner cases.

**Comment by egabancho** [comment]
The ACLs related with the collections are already taken care of by the Invenio-migrator https://github.com/inveniosoftware/invenio-migrator/blob/master/invenio_migrator/legacy/records.py#L110 .
But I guess they still need to be treated properly when loading the records, like here https://github.com/CERNDocumentServer/cds-videos/blob/cdslabs_qa/cds/modules/migrator/records.py#L93

---

We kept older versions of the records only accessible by admins because we couldn't calculate the ACLs properly https://github.com/CERNDocumentServer/cds-videos/blob/cdslabs_qa/cds/modules/migrator/records.py#L119
