### ISSUE TITLE
items: health check

### ISSUE THREAD

**Issue by kpsherva** [CERNDocumentServer/cds-migrator-kit#50]
- [ ] check if all items migrated
- [ ] check if item statuses are consistent
- [ ] check if barcodes are correct
- [ ] check if items are attached to correct locations

**Comment by agentilb** [comment]
The fields seem to be correctly migrated (barcode, medium, shelf, description) 

Here are the issues we have noticed: 

1) For records with some items having a specific medium, the other items have not been migrated: 
https://sandbox-cds-ils.web.cern.ch/backoffice/documents/848hy-2wm02
=> this record has 4 items as cd-rom 
But there are much more in reality:
https://cds.cern.ch/admin2/bibcirculation/item_search_result?f=barcode&p=CM-B00048083
The other items with standard medium (paper) have not been migrated. 

2) Not all the items have been migrated for a same record: 
https://sandbox-cds-ils.web.cern.ch/backoffice/documents/h1c9a-fqk98
https://cds.cern.ch/admin2/bibcirculation/item_search_result?f=barcode&p=CM-B00063634

3) Change of migration rules for "For reference only"
- This status should be kept only for items belonging to the LSL library
- exception: if one item is missing, then put status "Missing" and not "For reference only"

For all the other items, we ignore the "Reference" information, and migrate items as non reference items. With loan restriction 4 weeks.  

4) Confusion "Main location" "Internal location"
Is it necessary to display the main location on the book record, since at CERN we have only one?
https://sandbox-cds-ils.web.cern.ch/literature/vc5gj-md295
Or we should change the wording displayed: ex: "Available at CERN"
