### ISSUE TITLE
document: clean conference identifiers

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-migrator-kit#86]
where `962__n` is cern conference code, move it (if not already there) to respective `111__g` or `711__g` field. Since we changed the conference info to be an array, we cannot know to which of the conferences to assign the orphans identifiers. Same for the inspire cnum located in `0247__9` or `035__9` or `036__9`

**Comment by agentilb** [comment]
- [ ] Add CNUM to the 111__ field: done, in the field 111__i or 711__i

- [ ] Regarding 962, this is not used for the proceedings records, so it should be fine there. 
However, indeed there are 55 documents linking to Proceedings records with 962. In order to facilitate things, I have converted them in 775, relation "other". So except for the standards, the 962 field can be ignored.
